# Generated by Django 3.0.2 on 2020-02-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(blank=True, default='Dictation', max_length=256, null=True)),
                ('creator', models.EmailField(blank=True, max_length=254, null=True)),
                ('words', models.TextField(blank=True, null=True)),
                ('marked_words', models.TextField(blank=True, null=True)),
                ('type_of_questions', models.CharField(blank=True, default='quiz', max_length=256)),
                ('amount_of_words', models.IntegerField(blank=True, default=2)),
                ('amount_of_words_for_dictation', models.IntegerField(blank=True, default=2)),
            ],
        ),
        migrations.CreateModel(
            name='StudySets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('language_to', models.CharField(blank=True, max_length=256, null=True)),
                ('language_from', models.CharField(blank=True, max_length=256, null=True)),
                ('words', models.TextField(blank=True, null=True)),
                ('creator', models.EmailField(blank=True, max_length=254, null=True)),
                ('percent_of_studying', models.IntegerField(blank=True, null=True)),
                ('studied', models.BooleanField(blank=True, default=False)),
                ('amount_of_words', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
