# Generated by Django 3.0.3 on 2020-03-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_user'), ('api', '0003_auto_20200214_1916'), ('api', '0004_remove_user_marks'), ('api', '0005_studysets_marked_words'), ('api', '0006_auto_20200229_2116'), ('api', '0007_dictationmark_updated_at'), ('api', '0008_auto_20200305_0852'), ('api', '0009_auto_20200305_0855'), ('api', '0010_auto_20200308_1627'), ('api', '0008_remove_dictationmark_updated_at'), ('api', '0011_merge_20200308_2018'), ('api', '0012_auto_20200308_2018'), ('api', '0013_auto_20200308_2029')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(null=True, unique=True)),
                ('name', models.CharField(default='Dictation', max_length=256)),
                ('creator', models.EmailField(max_length=254)),
                ('words', models.TextField()),
                ('marked_words', models.TextField(blank=True, null=True)),
                ('type_of_questions', models.CharField(default='quiz', max_length=256)),
                ('amount_of_words', models.IntegerField(default=2)),
                ('amount_of_words_for_dictation', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DictationMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('dictation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dictation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='dictation',
            name='members',
            field=models.ManyToManyField(related_name='members', through='api.DictationMark', to='api.User'),
        ),
        migrations.AddField(
            model_name='dictation',
            name='language_from',
            field=models.CharField(default='en', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dictation',
            name='language_to',
            field=models.CharField(default='ru', max_length=256),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudySets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('language_to', models.CharField(max_length=256)),
                ('language_from', models.CharField(max_length=256)),
                ('words', models.TextField()),
                ('creator', models.EmailField(max_length=254)),
                ('percent_of_studying', models.IntegerField(blank=True, null=True)),
                ('studied', models.BooleanField(default=False)),
                ('amount_of_words', models.IntegerField()),
                ('marked_words', models.TextField(blank=True, default='', null=True)),
                ('synced', models.BooleanField(default=True)),
            ],
        ),
    ]
