# Generated by Django 3.0.3 on 2020-03-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0013_auto_20200308_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studysets',
            old_name='synced',
            new_name='sync_status',
        ),
    ]
