# Generated by Django 3.0.2 on 2020-02-14 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictation',
            name='amount_of_words',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='dictation',
            name='amount_of_words_for_dictation',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='dictation',
            name='code',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dictation',
            name='creator',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='dictation',
            name='name',
            field=models.CharField(default='Dictation', max_length=256),
        ),
        migrations.AlterField(
            model_name='dictation',
            name='type_of_questions',
            field=models.CharField(default='quiz', max_length=256),
        ),
        migrations.AlterField(
            model_name='dictation',
            name='words',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studysets',
            name='amount_of_words',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studysets',
            name='creator',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='studysets',
            name='language_from',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='studysets',
            name='language_to',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='studysets',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='studysets',
            name='studied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studysets',
            name='words',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='marks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='DictationMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('dictation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dictation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='dictation',
            name='members',
            field=models.ManyToManyField(related_name='members', through='api.DictationMark', to='api.User'),
        ),
    ]
