# Generated by Django 3.0.2 on 2020-03-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200309_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictation',
            name='question_time',
            field=models.IntegerField(default=0),
        ),
    ]
