# Generated by Django 3.0.2 on 2020-02-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200214_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='marks',
        ),
    ]
