# Generated by Django 3.0.2 on 2020-01-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
