# Generated by Django 3.0.2 on 2020-01-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysets',
            name='creator',
            field=models.EmailField(default='vlad120403@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
