# Generated by Django 3.0.2 on 2020-01-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200125_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysets',
            name='percent_of_studying',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysets',
            name='studied',
            field=models.BooleanField(default=False),
        ),
    ]
