# Generated by Django 3.0.3 on 2020-03-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200229_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictationmark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
