# Generated by Django 3.0.2 on 2020-01-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200126_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysets',
            name='count_of_words',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
