# Generated by Django 3.0.3 on 2020-03-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dictationmark_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictationmark',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
