# Generated by Django 3.0.2 on 2020-01-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_studysets_count_of_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studysets',
            old_name='count_of_words',
            new_name='amount_of_words',
        ),
    ]
