# Generated by Django 3.0.2 on 2020-02-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200126_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('creator', models.EmailField(max_length=254)),
                ('words', models.TextField()),
                ('members', models.TextField()),
            ],
        ),
    ]
