# Generated by Django 3.0.3 on 2020-03-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200305_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictation',
            name='language_from',
            field=models.CharField(default='en', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dictation',
            name='language_to',
            field=models.CharField(default='ru', max_length=256),
            preserve_default=False,
        ),
    ]
