# Generated by Django 3.0.2 on 2020-02-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200210_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictation',
            name='name',
            field=models.CharField(default='Dictation', max_length=256),
        ),
    ]
