# Generated by Django 3.0.3 on 2020-03-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_dictationmark_updated_at'),
        ('api', '0010_auto_20200308_1627'),
    ]

    operations = [
    ]
