# Generated by Django 3.0.3 on 2020-03-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20200308_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictationmark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
