# Generated by Django 3.0.2 on 2020-02-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_dictation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictation',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
