# Generated by Django 3.0.2 on 2020-03-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dictation_question_time'),
        ('api', '0012_dictationmark_updated_at'),
    ]

    operations = [
    ]
