# Generated by Django 3.0.2 on 2020-04-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_dictation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysets',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
